import {describe,it,expect} from 'vitest';
import {conclusionCard,conclusionChoices,requestCard,methodSummary,type Conclusion,type MethodState} from '../src/reuse-view';
const at='2026-09-30T00:00:00Z';
const source:Conclusion={id:'retained_one',taskId:'task_one',deliverable:{id:'delivery_one',version:2},sourceTaskVersion:4,artifactRefs:[],conclusion:'<script>private</script>',applicability:'Only synthetic metrics',scope:'owner_only',confirmedBy:'member_A',version:1,status:'current',createdAt:at,allowedActions:[]};
describe('F4a authorized reuse presentation',()=>{
 it('never renders withdrawn text, provenance IDs or an action link',()=>{const html=conclusionCard({...source,status:'revoked'});expect(html).toContain('结论已撤回');expect(html).not.toContain('private');expect(html).not.toContain('task_one');expect(html).not.toContain('href=');});
 it('escapes retained text and preserves an explicit scope distinct from lab sharing',()=>{const html=conclusionCard(source);expect(html).toContain('&lt;script&gt;');expect(html).not.toContain('<script>');expect(html).toContain('仅确认人本人');expect(conclusionCard({...source,scope:'source_readers'})).toContain('不会扩大到整个实验室');});
 it('does not select a source automatically, and a revised version has a different retained checkbox identity',()=>{const old=conclusionChoices([source],'reuse'),newer=conclusionChoices([{...source,version:2}],'reuse');expect(old).not.toContain(' checked');expect(old).toContain('name="reuse-retained_one-v1"');expect(newer).toContain('name="reuse-retained_one-v2"');expect(conclusionChoices([{...source,status:'needs_review'}],'reuse')).toContain('disabled');});
 it('completed generation summary does not claim that its plan is still a draft or remains unconfirmed',()=>{const html=requestCard({id:'req_one',status:'draft',planId:'plan_one',failure:null,version:3,createdAt:at,updatedAt:at});expect(html).toContain('查看方案当前状态');expect(html).not.toContain('尚未确认');expect(html).not.toContain('继续编辑');});
 it('distinguishes imported legacy method, immutable method version and activation generation',()=>{const state:MethodState={capabilityId:'text-evidence-checklist',generation:5,activeMethodVersion:2,enabled:false,ownerId:'member_A',allowedActions:[],methods:[{version:1,capabilityId:'text-evidence-checklist',labId:'lab_synthetic',config:{emphasis:'metrics',detail:'concise',citations:'exact_quote'},sampleIds:[],createdBy:null,createdAt:at,origin:'legacy_b3',usable:true,allowedActions:[],validationRunIds:[]}]};const html=methodSummary(state);expect(html).toContain('方法 v2');expect(html).toContain('启用配置第 5 代');expect(html).toContain('不冒充新方法已试跑');expect(html).toContain('当前已停用');});
});
