import type { ResponseFor, TaskModel } from '@research-agent-platform/contracts';
import { escapeHtml as e } from './view-model';
import { taskCard, planCard } from './collaboration-view';
export type Planning = ResponseFor<'getPlanRequest'>['data'];
export type Run = ResponseFor<'getRun'>['data'];
export const runLabels:Record<Run['status'],string>={queued:'已排队',running:'正在运行',waiting_input:'等待输入',failed:'失败',interrupted:'已中断',cancelled:'已取消',succeeded:'候选产物已生成'};
export function usage(value:Run['usageDetail']):string {
 return `<p class="fine">输入 tokens：${value?.inputTokens??'未知'} · 输出 tokens：${value?.outputTokens??'未知'} · 耗时：${value?value.elapsedMs+' ms':'未知'} · 费用：${value?.cost==null?'未知':e(String(value.cost)+' '+(value.currency??''))}</p>`;
}
export function planningView(p:Planning,name:(id:string)=>string):string {
 const states:Record<Planning['status'],string>={queued:'已排队',running:'正在生成',draft:'建议草案已保存',ready:'授权查询已返回',waiting_input:'等待输入',failed:'生成失败',interrupted:'生成已中断',cancelled:'生成已取消'};
 const reply=p.reply;
 const planState=reply?.plan?.status;
 const title=p.status==='draft'&&planState==='confirmed'?'方案已确认':p.status==='draft'&&planState==='superseded'?'方案已被替代':states[p.status];
 const intro:Record<Planning['status'],string>={queued:'生成在后台排队，稍后可从需求入口的本人生成请求找回。',running:'生成在后台进行，完成后显示完整、可编辑的草案。可以离开页面，稍后从需求入口的本人生成请求找回。',draft:'本次生成已完成。下方方案状态按本次服务读取显示。',ready:'以下查询结果来自授权服务。查看最新进展时请重新读取。',waiting_input:'本次请求正在等待输入，尚未完成生成。',failed:'本次生成失败，请查看原因或返回入口手工创建方案。',interrupted:'本次生成已中断。请读取最新状态；若用量或结果仍未知，请联系维护者，不要反复新建请求。仍可返回入口手工安排。',cancelled:'本次生成已取消，不会继续保存晚到的生成结果。'};
 const modelState=planState==='confirmed'?'模型生成方案 · 已由用户确认':planState==='superseded'?'模型生成方案 · 已被后续方案替代':'模型建议 · 尚未确认或承诺';
 const planTitle=planState==='confirmed'?'查看已确认方案':planState==='superseded'?'查看已替代方案':'继续编辑同一草案';
 const planNote=planState==='confirmed'?'方案已确认；成员是否承接、任务进展与验收以任务记录为准。已接受安排的调整须在任务中协商。':planState==='superseded'?'此方案已被替代，请查看当前有效安排；不能再次确认旧方案。':'日期、分工和缺材料仍需核对；打开后重新读取最新版本，再明确确认。此回复不自动派发。';
 return `<section class="flow"><a class="back" href="#/">← 返回入口</a><h1>${title}</h1><p class="fine">请求版本 ${p.version} · 更新 ${e(p.updatedAt)} · 可收藏当前链接，重新打开从服务读取。</p><p>${intro[p.status]}</p>${p.failure?`<p class="alert" role="alert">${e(p.failure)}。可以返回入口手工创建方案；重新发起是新请求。</p>`:''}${usage(p.usage)}${reply?`<p class="banner">${reply.origin==='model_suggestion'?modelState:'授权服务事实 · 不由模型编造进度'} · 读取 ${e(reply.readAt)} · 回复契约 ${e(reply.replyVersion)}</p>${reply.gaps.length?`<section class="panel"><h2>${planState==='confirmed'||planState==='superseded'?'生成时的提示':'缺口与匹配依据'}</h2><ul>${reply.gaps.map(g=>`<li>${e(g)}</li>`).join('')}</ul></section>`:''}${reply.plan?`<h2>${planTitle}</h2>${planCard(reply.plan)}<p>${planNote}</p>`:''}${reply.intent!=='draft'?`<h2>${reply.intent==='find_work'?'可承接候选':'当前任务进展'}</h2><p class="fine">仅展示服务授权的任务；以公开资料与服务返回的缺口为依据，不推断私人能力或人员负荷。</p>${reply.tasks.map(t=>taskCard(t,name)).join('')||'<p>没有符合当前授权范围的结果。</p>'}${reply.truncated?'<p>仅返回前 20 项，更多任务请进入实验室总览。</p>':''}`:''}<p class="fine">历史回复只是读取时的建议或事实。所有动作进入对象后重新校验当前版本与权限。</p>`:''}${['queued','running','waiting_input','interrupted'].includes(p.status)?`<form data-form="cancel-planning" class="panel"><label>取消原因<textarea name="planning-cancel-reason" required maxlength="8000"></textarea></label><button>取消这次生成</button></form>`:''}<button type="button" data-action="refresh">读取最新状态</button></section>`;
}
export function runView(r:Run,task:TaskModel):string {
 const candidate=r.candidate;
 const nextStep:Record<Run['status'],string>={queued:'已交给后台排队。可以离开页面，稍后从任务中查看。',running:'后台正在处理。完成后请核对来源与缺口，再决定是否提交。',waiting_input:'请先上传并选择本任务获准使用的文本材料，再按当前允许的操作继续。',failed:'本次没有形成可提交的成果。请查看失败原因，修正材料或安排后重试；也可手工交付。',interrupted:'执行已中断，远端用量可能未知。请先读取最新状态、核对记录；结果或用量不确定时联系维护者。仅按服务允许的操作继续，也可人工交付。',cancelled:'本次运行已取消。不会把晚到结果当作新的交付；如需继续，请重新确认安排。',succeeded:r.candidateDeliverableId?'候选已提交。请在本任务的交付与验收记录中查看处理结果。':'请核对下方候选与原文。确认提交后仍需要人工验收。'};
 return `<article class="panel run" data-run="${e(r.id)}"><h3>${runLabels[r.status]}</h3><p>${nextStep[r.status]}</p><details class="technical-details"><summary>核对来源与运行版本</summary><p class="fine">运行 ${e(r.id)} · v${r.version} · 任务绑定 v${r.taskVersion} / 当前 v${task.version} · 尝试 ${r.attempt}/${r.maxAttempts}</p><p>${e(r.capability.id)} · 配置第 ${r.configurationGeneration??r.capability.version} 代 · 方法 ${r.methodVersion==null?'未报告':'v'+r.methodVersion}${r.methodTrial?' · 方法试跑':''} · ${e(r.provider)} / ${e(r.model)} · Harness ${e(r.harnessVersion)}</p><p class="fine">累计预算 ${r.budget.maxTokens} tokens / ${r.budget.maxSeconds} 秒；${r.nextAttemptAt?'服务计划下次尝试 '+e(r.nextAttemptAt):'没有自动重试计划'}。未知用量不当作零。</p>${usage(r.usageDetail)}<p>输入：${r.inputs.map(i=>`${e(i.id)} v${i.version} · SHA256 ${e(i.sha256)}`).join('；')||'尚无已授权文本材料'}</p><p>明确选用的结论：${(r.conclusionRefs??[]).map(ref=>`<a href="#/conclusions/${e(ref.id)}">结论 v${ref.version}（${e(ref.id)}）</a>`).join('、')||'无'}</p></details>${r.failure?`<p class="alert">${e(r.failure)}</p>`:''}${candidate?`<section class="candidate"><h4>${e(candidate.title)}</h4><p class="banner">可审查候选，不等于交付已提交或任务已验收。引文匹配原材料，不代表外部科学核验。</p>${candidate.items.map(item=>`<section><h4>${e(item.requirement)}</h4><p>${item.assessment==='gap'?'存在缺口':'有输入材料支持'}</p>${item.gap?`<p>${e(item.gap)}</p>`:''}${item.citations.map(c=>`<blockquote>${e(c.quote)}<footer>引用来源 ${e(c.artifactId)}（按本次授权材料、结论或样例核对）</footer></blockquote>`).join('')}</section>`).join('')}<ul>${candidate.limitations.map(l=>`<li>${e(l)}</li>`).join('')}</ul></section>`:''}${r.candidateDeliverableId?`<p>已提交为交付 ${e(r.candidateDeliverableId)}，验收结果以交付记录为准。</p>`:''}<div class="actions">${r.allowedActions.includes('submit_candidate')?`<button type="button" data-action="submit-run-${e(r.id)}">确认提交此候选为交付</button>`:''}${r.allowedActions.includes('retry')?`<button type="button" data-action="retry-run-${e(r.id)}">按原累计预算重试此运行</button><p class="fine">重试前请在下方“能力、材料与新运行授权”选择当前授权文本；重试使用原累计预算和原结论绑定；修改结论来源请重新授权新运行。</p>`:''}</div>${r.allowedActions.includes('cancel')?`<form data-form="cancel-run-${e(r.id)}"><label>取消原因<textarea name="run-cancel-${e(r.id)}" required maxlength="8000"></textarea></label><button>取消此运行</button></form>`:''}</article>`;
}
