import { z } from 'zod'
import * as m from './models.js'

const empty = z.strictObject({})
const id = z.strictObject({ id: m.Id })
const inviteId = z.strictObject({ id: m.Id, inviteId: m.Id })
const version = z.strictObject({ expectedVersion: m.Version })
const reason = version.extend({ reason: m.Text })
const snapshotQuery = z.strictObject({ snapshot: z.string().min(1).max(2048).optional() })
const snap = { snapshot: m.Snapshot.optional() }
const pagination = snapshotQuery.extend({ cursor: z.string().min(1).max(2048).optional(), limit: z.number().int().min(1).max(100).default(30) })
const headers = z.strictObject({ 'Idempotency-Key': z.string().regex(/^[A-Za-z0-9_-]{16,128}$/) })
const taskDetail = z.strictObject({ task: m.Task, assignments: z.array(m.Assignment).max(100), deliverables: z.array(m.Deliverable).max(100), executions: z.array(m.RunRecord).max(100), changes: z.array(m.ChangeProposal).max(100).optional(), dependencyImpacts: z.array(m.DependencyImpact).max(100).optional(), dependencyImpactsTruncated: z.boolean().optional(), artifacts: z.array(m.Artifact).max(100).optional() })
const overview = z.strictObject({ counts: z.strictObject({ unassigned: z.number().int().min(0), active: z.number().int().min(0), review: z.number().int().min(0), completed: z.number().int().min(0) }), acceptedDeliverables: z.number().int().min(0), submittedDeliverables: z.number().int().min(0), blockedTaskIds: z.array(m.Id).max(100), blockedTaskIdsTruncated: z.boolean(), pendingActions: z.strictObject({ invitationResponses: z.number().int().min(0), deliverableReviews: z.number().int().min(0), changeResponses: z.number().int().min(0).optional(), executionAttention: z.number().int().min(0).optional() }), updatedAt: m.Instant })

// Every request has params/query/headers/body. Query numbers are decoded by clients
// before parsing. HTTP cookies are deliberately not part of serializable fixtures.
function route<P extends z.ZodType, Q extends z.ZodType, B extends z.ZodType, R extends z.ZodType>(method: 'GET' | 'POST' | 'PATCH', path: string, stage: 'B0' | 'B1' | 'B2' | 'B2a' | 'B2b' | 'B3' | 'B4a' | 'B4' | 'B5b', params: P, query: Q, body: B, response: R, status: number, rule: string, access = 'session', keyed = method !== 'GET') {
  return { method, path: `/api/v1${path}`, stage, status, access, rule, implemented: stage === 'B0' || stage === 'B1' || stage === 'B2a' || stage === 'B2b' || stage === 'B3' || stage === 'B4a' || stage === 'B5b', request: z.strictObject({ params, query, headers: keyed ? headers : empty, body }), response,
    errors: m.ErrorResponse, errorStatuses: m.errorStatus, idempotent: keyed }
}
export const routes = {
  live: route('GET', '/health/live', 'B0', empty, empty, z.null(), m.data(m.Health), 200, 'Process liveness only.', 'public'),
  ready: route('GET', '/health/ready', 'B0', empty, empty, z.null(), m.data(m.Health), 200, '503 with same health schema if database migration/write probe or blob read/write probe fails.', 'public'),
  login: route('POST', '/auth/login', 'B1', empty, empty, z.strictObject({ username: z.string().min(1).max(100), password: z.string().min(12).max(256) }), m.data(m.Member), 200, 'Verify provisioned password hash; rotate session; issue HttpOnly cookie. Invitation registration is a separate endpoint.', 'public', false),
  register: route('POST', '/auth/register', 'B5b', empty, empty, z.strictObject({ inviteCode:z.string().min(20).max(128).regex(/^[A-Za-z0-9_-]+$/), username:z.string().min(1).max(100).regex(/^[A-Za-z0-9_-]+$/), displayName:z.string().trim().min(1).max(200), password:z.string().min(16).max(256) }), m.data(z.strictObject({registered:z.literal(true),username:z.string().min(1).max(100)})), 201, 'Same-origin invitation-only account creation. No client lab/role/member ID; valid non-revoked invitation required. Account, membership, use count and retry receipt are atomic. No session issued; sign in afterwards. Never persists raw code or password.', 'public'),
  session: route('GET', '/auth/session', 'B1', empty, empty, z.null(), m.data(z.strictObject({ member: m.Member, csrfToken: m.Id, expiresAt: m.Instant, isLabManager: z.boolean() })), 200, 'Session DB lookup; expiry and revocation checked; manager flag is server-authoritative.'),
  logout: route('POST', '/auth/logout', 'B1', empty, empty, empty, m.data(z.strictObject({ loggedOut: z.literal(true) })), 200, 'Revoke current session and clear cookie; Origin and CSRF required.', 'session', false),
  managerInvites: route('GET', '/labs/{id}/registration-invites', 'B5b', id, empty, z.null(), m.data(z.strictObject({ invites:z.array(m.RegistrationInvite).max(50), truncated:z.boolean() })), 200, 'Current lab manager only; metadata for 50 latest invites, never raw codes or hashes.'),
  createManagerInvite: route('POST', '/labs/{id}/registration-invites', 'B5b', id, empty, z.strictObject({ expiresAt:m.Instant, maxUses:z.number().int().min(1).max(50) }), m.data(z.strictObject({ invite:m.RegistrationInvite, code:z.string().min(20).max(128) })), 201, 'Current lab manager only; code returned on creation or exact idempotent retry, never stored raw. CSRF and same-Origin required.'),
  revokeManagerInvite: route('POST', '/labs/{id}/registration-invites/{inviteId}/revoke', 'B5b', inviteId, empty, empty, m.data(m.RegistrationInvite), 200, 'Current lab manager only; revoke same-lab invite idempotently. CSRF and same-Origin required.'),
  me: route('GET', '/me', 'B1', empty, snapshotQuery, z.null(), m.data(m.Member).extend(snap), 200, 'Current authenticated member.'),
  members: route('GET', '/labs/{id}/members', 'B1', id, pagination, z.null(), m.page(m.Member).extend(snap), 200, 'Lab membership; only public profile and visible commitments.'),
  availability: route('PATCH', '/me/availability', 'B2a', empty, empty, version.extend({ availability: m.Availability.nullable() }), m.data(m.Member), 200, 'Self; transaction checks member version, server replaces updatedAt.'),
  plans: route('GET', '/plans', 'B2a', empty, pagination.extend({ status: z.enum(['draft', 'confirmed', 'superseded', 'all']).default('draft') }), z.null(), m.page(m.PlanSummary).extend({ snapshot: m.Snapshot }), 200, 'Owner and lab only before sorting/page; newest createdAt then id descending. Default draft; confirmed moves out, status=confirmed/all explicitly retrieves history. No tasks created by reading.'),
  actionItems: route('GET', '/labs/{id}/action-items', 'B2a', id, pagination.extend({ kind: z.enum(['all', 'invitation_response', 'deliverable_review', 'change_response', 'execution_attention']).default('all') }), z.null(), m.page(m.ActionItem).extend({ snapshot: m.Snapshot }), 200, 'Current actor only; actionable pending invitation or latest submitted revision requiring review. ACL first; newest task createdAt/id. Recheck versions on commands.'),
  createPlan: route('POST', '/plans', 'B1', empty, empty, m.PlanInput, m.data(m.Plan), 201, 'Lab member; create draft only, no assignments or dispatch.'),
  getPlan: route('GET', '/plans/{id}', 'B1', id, snapshotQuery, z.null(), m.data(m.Plan).extend(snap), 200, 'Owner only; shared tasks use separate projection.'),
  editPlan: route('PATCH', '/plans/{id}', 'B1', id, empty, version.extend(m.PlanInput.shape), m.data(m.Plan), 200, 'Owner; draft only; check version; never modify accepted commitments.'),
  confirmPlan: route('POST', '/plans/{id}/confirm', 'B1', id, empty, version, m.data(z.strictObject({ plan: m.Plan, taskIds: z.array(m.Id).max(100) })), 200, 'Owner; draft; validate graph, authorized inputs and public capability. One transaction: plan version, stable item/task IDs, assignments, events, outbox, idempotency result.'),
  tasks: route('GET', '/tasks', 'B1', empty, pagination.extend({ labId: m.Id, scope: z.enum(['lab', 'mine']), status: m.TaskStatus.optional() }), z.null(), m.page(z.union([m.Task, m.TaskSummary])).extend(snap), 200, 'Filter ACL before paging; mine = initiator/lead/participant/reviewer/pending invitee. Invitees and claimers receive only summary until authorized.'),
  task: route('GET', '/tasks/{id}', 'B1', id, snapshotQuery, z.null(), m.data(z.union([taskDetail, m.TaskSummary])).extend(snap), 200, 'ACL-specific projection; no private methods/IDs.'),
  invite: route('POST', '/tasks/{id}/invitations', 'B1', id, empty, version.extend({ memberId: m.Id, scope: m.Text, schedule: m.Schedule }), m.data(m.Assignment), 201, 'Initiator; unassigned/awaiting_acceptance and vacant lead; one transaction creates pending invitation, task version and event/outbox. Not a commitment.'),
  invitationDecision: route('POST', '/invitations/{id}/decision', 'B1', id, empty, version.extend({ expectedTaskVersion: m.Version, decision: z.enum(['accepted', 'declined']), comment: m.Text.nullable(), committed: m.Dated.nullable().optional() }), m.data(m.Assignment), 200, 'Invitee only; pending, active task. Lock task slot and assignment; acceptance stores offered scope/time and opens authorized inputs; decline preserves history.'),
  claim: route('POST', '/tasks/{id}/claim', 'B1', id, empty, version.extend({ committed: m.Dated.nullable().optional() }), m.data(m.Assignment), 200, 'Eligible member; open vacant slot; BEGIN IMMEDIATE, ACL, occupied slot check before version check; losing claim = ALREADY_CLAIMED with no winner private details.'),
  start: route('POST', '/tasks/{id}/start', 'B1', id, empty, version, m.data(m.Task), 200, 'Accepted lead; ready/changes_requested; validate dependencies; task+version+event+dedup transaction.'),
  block: route('POST', '/tasks/{id}/block', 'B2b', id, empty, version.extend({ reason: m.Text, requestedMemberId: m.Id.nullable(), requestedAction: m.Text }), m.data(m.Task), 200, 'Lead; ready/in_progress/changes_requested; save prior state server-side as resumeStatus.'),
  resume: route('POST', '/tasks/{id}/resume', 'B2b', id, empty, version, m.data(m.Task), 200, 'Lead; blocked only; recheck accepted dependency revisions and unresolved impacts, restore stored state, clear blocker.'),
  submit: route('POST', '/tasks/{id}/deliverables', 'B1', id, empty, version.extend({ summary: m.Text, artifactRefs: z.array(m.Id).max(100), sources: z.array(m.Source).max(100) }), m.data(m.Deliverable), 201, 'Lead/authorized participant; in_progress/changes_requested; verify attachments; allocate revision, set in_review and event atomically. No private method required.'),
  review: route('POST', '/deliverables/{id}/review', 'B1', id, empty, version.extend({ expectedTaskVersion: m.Version, revision: m.Version, decision: z.enum(['accepted', 'changes_requested']), comment: m.Text }), m.data(m.Deliverable), 200, 'Reviewer; task in_review, current submitted revision only; review+task completed/changes_requested+events+dedup atomic. Sharing is separate.'),
  proposeChange: route('POST', '/tasks/{id}/change-proposals', 'B2b', id, empty, version.extend({ scope: m.Text, dependencies: z.array(m.Dependency).max(100), goal: m.Text, acceptanceCriteria: m.Text, schedule: m.Schedule, proposedLeadId: m.Id.nullable(), reason: m.Text }), m.data(m.ChangeProposal), 201, 'Initiator/lead; accepted lead required; freeze initiator/reviewer/accepted lead; proposer explicitly accepts. Scope, schedule and dependencies unchanged until all accept; completed work reopens on application. Lead replacement uses withdraw+invitation; different proposedLeadId is 501.'),
  decideChange: route('POST', '/change-proposals/{id}/decision', 'B2b', id, empty, version.extend({ decision: z.enum(['accepted', 'declined']) }), m.data(m.ChangeProposal), 200, 'Required acceptor; pending only. Any decline rejects; all accept applies atomically if original task version still matches, otherwise superseded by the intervening task mutation; VERSION_CONFLICT. Old terms persist until then.'),
  withdraw: route('POST', '/tasks/{id}/withdraw', 'B2b', id, empty, reason.extend({ transferToMemberId: m.Id.nullable(), remainingScope: m.Text }), m.data(z.strictObject({ taskId: m.Id, taskVersion: m.Version, status: z.literal('withdrawn') })), 200, 'Accepted member; nonterminal; retain old record, revoke member task access unless independent role, free lead slot, halt dispatch; successor receives new invitation and must accept.'),
  cancelTask: route('POST', '/tasks/{id}/cancel', 'B2b', id, empty, reason, m.data(m.Task), 200, 'Initiator; nonterminal only; task/assignments/outbox cancellation and execution fence increment atomic; no promise to undo external effects.'),
  overview: route('GET', '/labs/{id}/overview', 'B2a', id, snapshotQuery.extend({ scope: z.enum(['lab', 'mine']) }), z.null(), m.data(overview).extend({ snapshot: m.Snapshot }), 200, 'One read snapshot; ACL before counts; no cancelled in four columns; blocked IDs capped with truncation flag; members/tasks/action items separately paginated under returned snapshot. Deliverable counts include all revisions on full-access tasks only.'),
  revokeAccess: route('POST', '/tasks/{id}/revoke-access', 'B2b', id, empty, reason.extend({ memberId: m.Id }), m.data(m.Task), 200, 'Initiator; cannot revoke initiator/reviewer. Revoke target ACL, end commitment and pending offers, supersede changes, retain history and stop pending dispatch. Cache replay rechecks live authority.'),
  revokeArtifact: route('POST', '/artifacts/{id}/revoke', 'B2b', id, empty, reason, m.data(m.Artifact), 200, 'Task initiator; globally revoke attachment content; retain immutable metadata and delivery version references. Old upload/submit/review cached replies cannot restore attachment access.'),
  acknowledgeImpacts: route('POST', '/tasks/{id}/dependency-impacts/acknowledge', 'B2b', id, empty, version.extend({ impactIds: z.array(m.Id).min(1).max(100), comment: m.Text }), m.data(m.Task), 200, 'Lead/reviewer explicitly reassesses preserved downstream results after dependencies are valid; acknowledge named impacts, never erase history or auto resume.'),
  events: route('GET', '/tasks/{id}/events', 'B2b', id, pagination, z.null(), m.page(m.TaskEvent).extend(snap), 200, 'Task ACL before sequence paging; reconnect polling 5s; expired cursor 410 then refetch task and events.'),
  upload: route('POST', '/artifacts', 'B2b', empty, empty, z.strictObject({ taskId: m.Id, expectedVersion: m.Version, filename: m.Title, mediaType: z.enum(['text/plain', 'application/pdf', 'image/png']), contentBase64: z.string().min(4).max(13981016).regex(/^[A-Za-z0-9+/]+={0,2}$/).refine(value => value.length % 4 === 0, 'base64 length must be divisible by four') }), m.data(m.Artifact), 201, 'Task writer; decoded size 1..10MiB, sniff type; private blob file plus transactional metadata/dedup; rollback cleanup, crash orphans remain inaccessible until maintenance. Never trust filename as path.'),
  artifact: route('GET', '/artifacts/{id}', 'B2b', id, snapshotQuery, z.null(), m.data(m.Artifact).extend(snap), 200, 'Recheck current task ACL, including on retries; no storage key or signed URL.'),
  content: route('GET', '/artifacts/{id}/content', 'B2b', id, empty, z.null(), z.instanceof(Uint8Array), 200, 'Binary attachment; Content-Type stored mediaType; Content-Disposition attachment; nosniff; Cache-Control private,no-store. Recheck ACL; range unsupported.'),
  planRequest: route('POST', '/planning-requests', 'B3', empty, empty, z.strictObject({ labId: m.Id, prompt: m.Text, conclusionRefs: z.array(m.ObjectRef).max(10).default([]), intent: z.enum(['auto','draft','progress','find_work']).default('auto'), plan: m.ObjectRef.nullable().default(null), taskIds: z.array(m.Id).max(20).default([]), inputArtifactIds: z.array(m.Id).max(10), budget: m.Budget }), m.data(m.PlanningRequest), 202, 'Lab member; model availability and authorized inputs checked; create dedicated execution intent; explicit facts need no model; model output validated, only draft, no confirm.'),
  getPlanRequest: route('GET', '/planning-requests/{id}', 'B3', id, empty, z.null(), m.data(m.PlanningRequest), 200, 'Request owner only; failed partial output is not confirmed plan.'),
  run: route('POST', '/tasks/{id}/runs', 'B3', id, empty, version.extend({ capability: m.PublicCapabilityRef, budget: m.Budget, inputArtifactIds: z.array(m.Id).max(10), conclusionRefs: z.array(m.ObjectRef).max(10).default([]) }), m.data(m.RunRecord), 202, 'Lead; ready/in_progress/changes_requested; live public capability+ACL+dependencies+budget; unique active execution, dedicated execution intent and dedup in transaction.'),
  getRun: route('GET', '/runs/{id}', 'B3', id, empty, z.null(), m.data(m.RunRecord), 200, 'Task ACL; public run only; private runs separate owner store.'),
  cancelRun: route('POST', '/runs/{id}/cancel', 'B3', id, empty, reason, m.data(m.RunRecord), 200, 'Lead/initiator; queued/running/waiting_input; fence increment+cancel intent+event atomic. Late completion cannot change state.'),
  publicCapabilities: route('GET', '/public-capabilities', 'B3', empty, empty, z.null(), m.page(m.Capability), 200, 'Current lab configured built-in capabilities only; never scans private methods. Availability is configuration, not a successful model-call claim.'),
  retryRun: route('POST', '/runs/{id}/retry', 'B3', id, empty, version.extend({ expectedTaskVersion: m.Version, inputArtifactIds: z.array(m.Id).max(10) }), m.data(m.RunRecord), 202, 'Lead explicitly reauthorizes current inputs/task; shared total attempt and token budget retained; uncertain usage forbids automatic retry.'),
  submitCandidate: route('POST', '/runs/{id}/submit', 'B3', id, empty, version.extend({ expectedTaskVersion: m.Version }), m.data(m.Deliverable), 201, 'Lead confirms validated candidate as a delivery; current authority, input versions, dependencies and task version checked again; reviewer still decides acceptance.'),
  cancelPlanning: route('POST', '/planning-requests/{id}/cancel', 'B3', id, empty, reason, m.data(m.PlanningRequest), 200, 'Owner; cancellation fences late model output.'),
  planningRequests: route('GET', '/planning-requests', 'B4a', empty, pagination, z.null(), m.page(m.PlanningSummary).extend({total:z.number().int().nonnegative(),...snap}), 200, 'Owner-only SQL authorization before count/page; inaccessible sources remove rows; no raw prompt. Current generation state remains separate from current plan state.'),
  conclusions: route('GET', '/conclusions', 'B4a', empty, pagination.extend({taskId:m.Id.optional()}), z.null(), m.page(m.RetainedConclusion).extend({total:z.number().int().nonnegative(),...snap}), 200, 'Current source permission and explicit scope before count/page; stale versions visible with needs_review; withdrawn rows hidden.'),
  retainConclusion: route('POST', '/tasks/{id}/conclusions', 'B4a', id, empty, version.extend(m.ConclusionInput.shape), m.data(m.RetainedConclusion), 201, 'Reviewer explicitly retains accepted delivery; original review does not share feedback. Selected artifact versions must belong to delivery.'),
  conclusion: route('GET', '/conclusions/{id}', 'B4a', id, empty, z.null(), m.data(m.RetainedConclusion), 200, 'Live source and scope authorization; head revision with current freshness.'),
  conclusionHistory: route('GET', '/conclusions/{id}/history', 'B4a', id, empty, z.null(), m.ConclusionHistory, 200, 'Live source authorization on every immutable revision; withdrawal hides all content, audit rows remain.'),
  reviseConclusion: route('POST', '/conclusions/{id}/revisions', 'B4a', id, empty, version.extend({expectedTaskVersion:m.Version}).extend(m.ConclusionInput.shape), m.data(m.RetainedConclusion), 201, 'Original confirmer; append immutable revision against newly accepted delivery; no silent replacement in consumers.'),
  revokeConclusion: route('POST', '/conclusions/{id}/revoke', 'B4a', id, empty, reason, m.data(z.strictObject({id:m.Id,version:m.Version,status:z.literal('revoked')})), 200, 'Original confirmer/current source reviewer; blocks history/cache/derivatives and dispatch, no promise to recall downloads.'),
  createSample: route('POST', '/tasks/{id}/public-method-feedback', 'B4a', id, empty, version.extend({deliverable:m.ObjectRef,decision:z.enum(['share_selected','decline']),selectedText:m.Text.nullable(),authorizeLabUse:z.boolean()}), m.data(m.FeedbackSample), 201, 'Explicit selected excerpt only. Initial release requires same actor submitter AND reviewer; maintainer receives excerpt, not source task rights.'),
  samples: route('GET', '/public-text-method/samples', 'B4a', empty, pagination, z.null(), m.page(m.FeedbackSample).extend({total:z.number().int().nonnegative(),...snap}), 200, 'Capability owner only; authorized available excerpts, never arbitrary task material.'),
  taskSamples: route('GET', '/tasks/{id}/public-method-feedback', 'B4a', id, pagination, z.null(), m.page(m.FeedbackSample).extend({total:z.number().int().nonnegative(),...snap}), 200, 'Current full task access; own grants/declines only before count/page. Unusable or withdrawn excerpts are redacted. Grantor may revoke a stored active grant even when its source needs review; no maintainer authority implied.'),
  revokeSample: route('POST', '/public-text-method/samples/{id}/revoke', 'B4a', id, empty, reason, m.data(z.strictObject({id:m.Id,version:m.Version,status:z.literal('revoked')})), 200, 'Grantor only; invalidates dependent method versions and trial derivatives, disables active dependent version.'),
  publicMethods: route('GET', '/public-text-method', 'B4a', empty, empty, z.null(), m.data(m.MethodState), 200, 'Existing capability owner only; immutable controlled configuration, no private capability catalog.'),
  createMethod: route('POST', '/public-text-method/versions', 'B4a', empty, empty, version.extend({config:m.MethodConfig,sampleIds:z.array(m.Id).min(1).max(10)}), m.data(m.PublicMethod), 201, 'Owner; expectedVersion is configuration generation; append immutable candidate based only on active explicitly granted samples.'),
  trialMethod: route('POST', '/public-text-method/trials', 'B4a', empty, empty, version.extend({methodVersion:m.Version,taskId:m.Id,expectedTaskVersion:m.Version,budget:m.Budget}), m.data(m.RunRecord), 202, 'Owner and target task lead; real durable Harness trial, selected granted samples only. Does not activate or submit a delivery.'),
  activateMethod: route('POST', '/public-text-method/activate', 'B4a', empty, empty, version.extend({methodVersion:m.Version,runId:m.Id,confirm:z.literal(true)}), m.data(m.MethodState), 200, 'Owner; exact candidate successful real Harness trial plus explicit human confirmation; increment configuration generation, never rewrite method.'),
  disableMethod: route('POST', '/public-text-method/disable', 'B4a', empty, empty, reason, m.data(m.MethodState), 200, 'Owner; increment configuration generation, fence queued/running old generation. History remains bound to original method.'),
  methodEvents: route('GET', '/public-text-method/events', 'B4a', empty, pagination, z.null(), m.page(m.MethodEvent).extend(snap), 200, 'Owner-only configuration and validation audit, legacy import is not fabricated publication.'),
  capabilities: route('GET', '/capabilities', 'B4', empty, pagination.extend({ labId: m.Id, scope: z.enum(['public', 'mine']) }), z.null(), m.page(m.Capability), 200, 'Public query only lab_public; mine only owner. Never scan other private capabilities for matching.'),
  createCapability: route('POST', '/capabilities', 'B4', empty, empty, z.strictObject({ labId: m.Id, name: m.Title, inputContract: m.Text, outputContract: m.Text }), m.data(m.Capability), 201, 'Member; owner from session; default private/draft; no publish flag accepted.'),
  testCapability: route('POST', '/capabilities/{id}/test-runs', 'B4', id, empty, version.extend({ input: m.Text, budget: m.Budget }), m.data(z.strictObject({ id: m.Id, capabilityId: m.Id, capabilityVersion: m.Version, status: m.ExecutionStatus, result: m.Text.nullable() })), 202, 'Owner or expressly authorized maintainer; private test result in owner store; actual harness prerequisite.'),
  publish: route('POST', '/capabilities/{id}/publish', 'B4', id, empty, version.extend({ validationResultId: m.Id, authorizePublication: z.literal(true) }), m.data(m.Capability), 200, 'Owner or explicit publishing grant; exact version successful real validation; no organization-role override.'),
  disable: route('POST', '/capabilities/{id}/disable', 'B4', id, empty, reason, m.data(m.Capability), 200, 'Owner/explicit maintainer; set disabled/version+fence new runs+events; retain prior shared copies.'),
  knowledge: route('GET', '/tasks/{id}/knowledge', 'B4', id, pagination, z.null(), m.page(m.Knowledge), 200, 'Task ACL and explicit authorized conclusions only.'),
  feedback: route('POST', '/tasks/{id}/feedback-sharing', 'B4', id, empty, version.extend({ deliverableId: m.Id, revision: m.Version, decision: z.enum(['share_selected', 'decline', 'revoke']), selectedText: m.Text.nullable(), purpose: z.literal('public_capability_improvement') }), m.data(m.Sharing), 200, 'Rights holder only; separate from review; only selected text; revoke stops future reuse, cannot erase prior copies. Detailed revision policy gated at B4.'),
} as const
export type RouteName = keyof typeof routes
export type RequestFor<K extends RouteName> = z.input<(typeof routes)[K]['request']>
export type ResponseFor<K extends RouteName> = z.output<(typeof routes)[K]['response']>
