import { z } from 'zod'
import * as m from './models.js'

const empty = z.strictObject({})
const id = z.strictObject({ id: m.Id })
const version = z.strictObject({ expectedVersion: m.Version })
const reason = version.extend({ reason: m.Text })
const pagination = z.strictObject({ cursor: z.string().min(1).max(2048).optional(), limit: z.number().int().min(1).max(100).default(30) })
const headers = z.strictObject({ 'Idempotency-Key': z.string().regex(/^[A-Za-z0-9_-]{16,128}$/) })
const taskDetail = z.strictObject({ task: m.Task, assignments: z.array(m.Assignment).max(100), deliverables: z.array(m.Deliverable).max(100), executions: z.array(m.Execution).max(100) })
const overview = z.strictObject({ counts: z.strictObject({ unassigned: z.number().int().min(0), active: z.number().int().min(0), review: z.number().int().min(0), completed: z.number().int().min(0) }), acceptedDeliverables: z.number().int().min(0), submittedDeliverables: z.number().int().min(0), blockedTaskIds: z.array(m.Id).max(100), members: z.array(m.Member).max(100), updatedAt: m.Instant })

// Every request has params/query/headers/body. Query numbers are decoded by clients
// before parsing. HTTP cookies are deliberately not part of serializable fixtures.
function route<P extends z.ZodType, Q extends z.ZodType, B extends z.ZodType, R extends z.ZodType>(method: 'GET' | 'POST' | 'PATCH', path: string, stage: 'B0' | 'B1' | 'B2' | 'B3' | 'B4', params: P, query: Q, body: B, response: R, status: number, rule: string, access = 'session', keyed = method !== 'GET') {
  return { method, path: `/api/v1${path}`, stage, status, access, rule, implemented: stage === 'B0', request: z.strictObject({ params, query, headers: keyed ? headers : empty, body }), response,
    errors: m.ErrorResponse, errorStatuses: m.errorStatus, idempotent: keyed }
}
export const routes = {
  live: route('GET', '/health/live', 'B0', empty, empty, z.null(), m.data(m.Health), 200, 'Process liveness only.', 'public'),
  ready: route('GET', '/health/ready', 'B0', empty, empty, z.null(), m.data(m.Health), 200, '503 with same health schema if database migration/write probe or blob read/write probe fails.', 'public'),
  login: route('POST', '/auth/login', 'B1', empty, empty, z.strictObject({ username: z.string().min(1).max(100), password: z.string().min(12).max(256) }), m.data(m.Member), 200, 'Verify provisioned password hash; rotate session; issue HttpOnly cookie. No self registration.', 'public', false),
  session: route('GET', '/auth/session', 'B1', empty, empty, z.null(), m.data(z.strictObject({ member: m.Member, csrfToken: m.Id, expiresAt: m.Instant })), 200, 'Session DB lookup; expiry and revocation checked.'),
  logout: route('POST', '/auth/logout', 'B1', empty, empty, empty, m.data(z.strictObject({ loggedOut: z.literal(true) })), 200, 'Revoke current session and clear cookie; Origin and CSRF required.', 'session', false),
  me: route('GET', '/me', 'B1', empty, empty, z.null(), m.data(m.Member), 200, 'Current authenticated member.'),
  members: route('GET', '/labs/{id}/members', 'B1', id, pagination, z.null(), m.page(m.Member), 200, 'Lab membership; only public profile and visible commitments.'),
  availability: route('PATCH', '/me/availability', 'B2', empty, empty, version.extend({ availability: m.Availability.nullable() }), m.data(m.Member), 200, 'Self; transaction checks member version, server replaces updatedAt.'),
  createPlan: route('POST', '/plans', 'B1', empty, empty, m.PlanInput, m.data(m.Plan), 201, 'Lab member; create draft only, no assignments or dispatch.'),
  getPlan: route('GET', '/plans/{id}', 'B1', id, empty, z.null(), m.data(m.Plan), 200, 'Owner only; shared tasks use separate projection.'),
  editPlan: route('PATCH', '/plans/{id}', 'B1', id, empty, version.extend(m.PlanInput.shape), m.data(m.Plan), 200, 'Owner; draft only; check version; never modify accepted commitments.'),
  confirmPlan: route('POST', '/plans/{id}/confirm', 'B1', id, empty, version, m.data(z.strictObject({ plan: m.Plan, taskIds: z.array(m.Id).max(100) })), 200, 'Owner; draft; validate graph, authorized inputs and public capability. One transaction: plan version, stable item/task IDs, assignments, events, outbox, idempotency result.'),
  tasks: route('GET', '/tasks', 'B1', empty, pagination.extend({ labId: m.Id, scope: z.enum(['lab', 'mine']), status: m.TaskStatus.optional() }), z.null(), m.page(z.union([m.Task, m.TaskSummary])), 200, 'Filter ACL before paging; mine = initiator/lead/participant/reviewer/pending invitee. Invitees and claimers receive only summary until authorized.'),
  task: route('GET', '/tasks/{id}', 'B1', id, empty, z.null(), m.data(z.union([taskDetail, m.TaskSummary])), 200, 'ACL-specific projection; no private methods/IDs.'),
  invite: route('POST', '/tasks/{id}/invitations', 'B1', id, empty, version.extend({ memberId: m.Id, scope: m.Text, schedule: m.Schedule }), m.data(m.Assignment), 201, 'Initiator; unassigned/awaiting_acceptance and vacant lead; one transaction creates pending invitation, task version and event/outbox. Not a commitment.'),
  invitationDecision: route('POST', '/invitations/{id}/decision', 'B1', id, empty, version.extend({ expectedTaskVersion: m.Version, decision: z.enum(['accepted', 'declined']), comment: m.Text.nullable() }), m.data(m.Assignment), 200, 'Invitee only; pending, active task. Lock task slot and assignment; acceptance stores offered scope/time and opens authorized inputs; decline preserves history.'),
  claim: route('POST', '/tasks/{id}/claim', 'B1', id, empty, version, m.data(m.Assignment), 200, 'Eligible member; open vacant slot; BEGIN IMMEDIATE, ACL, occupied slot check before version check; losing claim = ALREADY_CLAIMED with no winner private details.'),
  start: route('POST', '/tasks/{id}/start', 'B1', id, empty, version, m.data(m.Task), 200, 'Accepted lead; ready/changes_requested; validate dependencies; task+version+event+dedup transaction.'),
  block: route('POST', '/tasks/{id}/block', 'B2', id, empty, version.extend({ reason: m.Text, requestedMemberId: m.Id.nullable(), requestedAction: m.Text }), m.data(m.Task), 200, 'Lead; ready/in_progress/changes_requested; save prior state server-side as resumeStatus.'),
  resume: route('POST', '/tasks/{id}/resume', 'B2', id, empty, version, m.data(m.Task), 200, 'Lead; blocked only; recheck dependencies/authorization, restore stored state, clear blocker.'),
  submit: route('POST', '/tasks/{id}/deliverables', 'B1', id, empty, version.extend({ summary: m.Text, artifactRefs: z.array(m.Id).max(100), sources: z.array(m.Source).max(100) }), m.data(m.Deliverable), 201, 'Lead/authorized participant; in_progress/changes_requested; verify attachments; allocate revision, set in_review and event atomically. No private method required.'),
  review: route('POST', '/deliverables/{id}/review', 'B1', id, empty, version.extend({ expectedTaskVersion: m.Version, revision: m.Version, decision: z.enum(['accepted', 'changes_requested']), comment: m.Text }), m.data(m.Deliverable), 200, 'Reviewer; task in_review, current submitted revision only; review+task completed/changes_requested+events+dedup atomic. Sharing is separate.'),
  proposeChange: route('POST', '/tasks/{id}/change-proposals', 'B2', id, empty, version.extend({ goal: m.Text, acceptanceCriteria: m.Text, schedule: m.Schedule, proposedLeadId: m.Id.nullable(), reason: m.Text }), m.data(m.ChangeProposal), 201, 'Initiator/lead; nonterminal task; freeze required acceptors = initiator, reviewer, all accepted affected members and proposed lead. No commitment changes yet.'),
  decideChange: route('POST', '/change-proposals/{id}/decision', 'B2', id, empty, version.extend({ decision: z.enum(['accepted', 'declined']) }), m.data(m.ChangeProposal), 200, 'Required acceptor; pending only. Any decline rejects; all accept applies atomically if original task version still matches, otherwise superseded + VERSION_CONFLICT. Old terms persist until then.'),
  withdraw: route('POST', '/tasks/{id}/withdraw', 'B2', id, empty, reason.extend({ transferToMemberId: m.Id.nullable(), remainingScope: m.Text }), m.data(m.Task), 200, 'Accepted member; nonterminal; retain old record, revoke member task access unless independent role, free lead slot, halt dispatch; successor receives new invitation and must accept.'),
  cancelTask: route('POST', '/tasks/{id}/cancel', 'B2', id, empty, reason, m.data(m.Task), 200, 'Initiator; nonterminal only; task/assignments/outbox cancellation and execution fence increment atomic; no promise to undo external effects.'),
  overview: route('GET', '/labs/{id}/overview', 'B2', id, z.strictObject({ scope: z.enum(['lab', 'mine']) }), z.null(), m.data(overview), 200, 'One read snapshot; ACL before counts; no cancelled in four columns; blocked IDs/member list capped 100; task list separately paginated.'),
  events: route('GET', '/tasks/{id}/events', 'B2', id, pagination, z.null(), m.page(m.TaskEvent), 200, 'Task ACL before sequence paging; reconnect polling 5s; expired cursor 410 then refetch task and events.'),
  upload: route('POST', '/artifacts', 'B2', empty, empty, z.strictObject({ taskId: m.Id, expectedVersion: m.Version, filename: m.Title, mediaType: z.enum(['text/plain', 'application/pdf', 'image/png']), contentBase64: z.string().min(4).max(13981016).regex(/^(?:[A-Za-z0-9+/]{4})*(?:[A-Za-z0-9+/]{2}==|[A-Za-z0-9+/]{3}=)?$/) }), m.data(m.Artifact), 201, 'Task writer; decoded size 1..10MiB, sniff type; stage blob then transaction metadata+dedup; sweep orphan blobs. Never trust filename as path.'),
  artifact: route('GET', '/artifacts/{id}', 'B2', id, empty, z.null(), m.data(m.Artifact), 200, 'Recheck current task ACL, including on retries; no storage key or signed URL.'),
  content: route('GET', '/artifacts/{id}/content', 'B2', id, empty, z.null(), z.instanceof(Uint8Array), 200, 'Binary attachment; Content-Type stored mediaType; Content-Disposition attachment; nosniff; Cache-Control private,no-store. Recheck ACL; range unsupported.'),
  planRequest: route('POST', '/planning-requests', 'B3', empty, empty, z.strictObject({ labId: m.Id, prompt: m.Text, inputArtifactIds: z.array(m.Id).max(100), budget: m.Budget }), m.data(m.PlanningRequest), 202, 'Lab member; model availability and authorized inputs checked; create queued request/outbox; model output validated, only draft, no confirm.'),
  getPlanRequest: route('GET', '/planning-requests/{id}', 'B3', id, empty, z.null(), m.data(m.PlanningRequest), 200, 'Request owner only; failed partial output is not confirmed plan.'),
  run: route('POST', '/tasks/{id}/runs', 'B3', id, empty, version.extend({ capability: m.PublicCapabilityRef, budget: m.Budget, inputArtifactIds: z.array(m.Id).max(100) }), m.data(m.Execution), 202, 'Lead; ready/in_progress/changes_requested; live public capability+ACL+dependencies+budget; unique active execution, outbox and dedup in transaction.'),
  getRun: route('GET', '/runs/{id}', 'B3', id, empty, z.null(), m.data(m.Execution), 200, 'Task ACL; public run only; private runs separate owner store.'),
  cancelRun: route('POST', '/runs/{id}/cancel', 'B3', id, empty, reason, m.data(m.Execution), 200, 'Lead/initiator; queued/running/waiting_input; fence increment+cancel intent+event atomic. Late completion cannot change state.'),
  capabilities: route('GET', '/capabilities', 'B4', empty, pagination.extend({ labId: m.Id, scope: z.enum(['public', 'mine']) }), z.null(), m.page(m.Capability), 200, 'Public query only lab_public; mine only owner. Never scan other private capabilities for matching.'),
  createCapability: route('POST', '/capabilities', 'B4', empty, empty, z.strictObject({ labId: m.Id, name: m.Title, inputContract: m.Text, outputContract: m.Text }), m.data(m.Capability), 201, 'Member; owner from session; default private/draft; no publish flag accepted.'),
  testCapability: route('POST', '/capabilities/{id}/test-runs', 'B4', id, empty, version.extend({ input: m.Text, budget: m.Budget }), m.data(z.strictObject({ id: m.Id, capabilityId: m.Id, capabilityVersion: m.Version, status: m.ExecutionStatus, result: m.Text.nullable() })), 202, 'Owner or expressly authorized maintainer; private test result in owner store; actual harness prerequisite.'),
  publish: route('POST', '/capabilities/{id}/publish', 'B4', id, empty, version.extend({ validationResultId: m.Id, authorizePublication: z.literal(true) }), m.data(m.Capability), 200, 'Owner or explicit publishing grant; exact version successful real validation; no organization-role override.'),
  disable: route('POST', '/capabilities/{id}/disable', 'B4', id, empty, reason, m.data(m.Capability), 200, 'Owner/explicit maintainer; set disabled/version+fence new runs+events; retain prior shared copies.'),
  knowledge: route('GET', '/tasks/{id}/knowledge', 'B4', id, pagination, z.null(), m.page(m.Knowledge), 200, 'Task ACL and explicit authorized conclusions only.'),
  feedback: route('POST', '/tasks/{id}/feedback-sharing', 'B4', id, empty, version.extend({ deliverableId: m.Id, revision: m.Version, decision: z.enum(['share_selected', 'decline', 'revoke']), selectedText: m.Text.nullable(), purpose: z.literal('public_capability_improvement') }), m.data(m.Sharing), 200, 'Rights holder only; separate from review; only selected text; revoke stops future reuse, cannot erase prior copies. Detailed revision policy gated at B4.'),
} as const
export type RouteName = keyof typeof routes
export type RequestFor<K extends RouteName> = z.input<(typeof routes)[K]['request']>
export type ResponseFor<K extends RouteName> = z.output<(typeof routes)[K]['response']>

